<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Product>Bitbucket Data Center [Beta]</Product>
        <Description>Bitbucket Data Center is a self-managed solution that provides source code collaboration for professional teams of any size</Description>
        <Version>1.0.0</Version>
        <PackageId>Apps.BitbucketDataCenter</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Blackbird.Applications.Sdk.Common" Version="2.17.0" />
        <PackageReference Include="Blackbird.Applications.Sdk.Utils" Version="1.1.0-rc.8709" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource CopyToOutputDirectory="Always" Include="image\icon.png" />
        <EmbeddedResource CopyToOutputDirectory="Always" Include="..\README.md" />
    </ItemGroup>

</Project>
